
```{r}
library(ggplot2)
```



```{r, echo = FALSE, fig.width=12, fig.height=6, fig.align='center'}
data(ToothGrowth)
tg <- ToothGrowth

g <- ggplot(tg,  aes(x = c(1:60), y = len), colour = supp)
g <- g + geom_point(aes(color = supp))  
g <- g + facet_grid(. ~ dose) + xlab("Observations") + ylab("Length")
g

```

Analysing based on **supp**

```{r}
vc <- tg[1:30,]$len
oj <- tg[31:60,]$len

test_by_supp <- sapply(data.frame(vc, oj), function(x){
    t.test(x)$conf.int
})

colnames(test_by_supp) <- c("VC", "OC")
rownames(test_by_supp) <- c("Lower", "Upper")
test_by_supp
```

Analysing based on **dose**
```{r}
dt_M <- data.frame(tg[1:10,]$len, tg[11:20,]$len, tg[21:30,]$len, tg[31:40,]$len, tg[41:50,]$len, tg[51:60,]$len)

test_result <- sapply(dt_M, function(x){
    t.test(x)$conf.int
})

colnames(test_result) <- c("VC_0.5", "VC_1.0", "VC_2.0", "OJ_0.5", "OJ_1.0", "OJ_2.0")
rownames(test_result) <- c("Lower", "Upper")

test_result

```

Two sample t-test

```{r}
dt_M <- data.frame(tg[1:10,]len, tg[31:40,]$len)
t.test(dt_M[,1], dt_M[,2], paired = TRUE)


```
