

```{r}
load(url("http://www.openintro.org/stat/data/ames.RData"))
population <- ames$Gr.Liv.Area
samp <- sample(population, 60)

```


```{r}
plot_ci <- function(lo, hi, m){
  par(mar=c(2, 1, 1, 1), mgp=c(2.7, 0.7, 0))
  k <- 50
  ci.max <- max(rowSums(matrix(c(-1*lo,hi),ncol=2)))

  xR <- m + ci.max*c(-1, 1)
  yR <- c(0, 41*k/40)

  plot(xR, yR, type='n', xlab='', ylab='', axes=FALSE)
  abline(v=m, lty=2, col='#00000088')
  axis(1, at=m, paste("mu = ",round(m,4)), cex.axis=1.15)
  #axis(2)
  for(i in 1:k){
    x <- mean(c(hi[i],lo[i]))
      ci <- c(lo[i],hi[i])
	  if(contains(lo[i],hi[i],m)==FALSE){
		  col <- "#F05133"
		  points(x, i, cex=1.4, col=col)
#		  points(x, i, pch=20, cex=1.2, col=col)
		  lines(ci, rep(i, 2), col=col, lwd=5)
	  }
	  col <- 1
  	points(x, i, pch=20, cex=1.2, col=col)
	  lines(ci, rep(i, 2), col=col)
  }
}

```

```{r}
# The 'ames' data frame is already loaded into the workspace

# Initialize 'samp_mean', 'samp_sd' and 'n':
samp_mean <- rep(NA, 50)
samp_sd <- rep(NA, 50)
n <- 60

# For loop goes here:
for (i in 1:50) {
  samp <- sample(population, n) 
  samp_mean[i] <- mean(samp)
  samp_sd[i] <- sd(samp)
}

# Calculate the interval bounds here:
lower <- samp_mean - 1.96* (samp_sd/sqrt(n))
upper <- samp_mean + 1.96* (samp_sd/sqrt(n))

# Plotting the confidence intervals:
pop_mean <- mean(population)
plot_ci(lower, upper, pop_mean)


```
